/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kalkulatorsederhana;

/**
 *
 * @author ardian
 */
public class NewJFrame extends javax.swing.JFrame {
String Angka;
double Jumlah,Angka1,Angka2;
int Pilih;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtHasil = new javax.swing.JTextField();
        BtnCancel1 = new javax.swing.JButton();
        BtnBagi = new javax.swing.JButton();
        BtnAngka7 = new javax.swing.JButton();
        BtnAngka8 = new javax.swing.JButton();
        BtnAngka9 = new javax.swing.JButton();
        BtnKali = new javax.swing.JButton();
        BtnAngka4 = new javax.swing.JButton();
        BtnAngka5 = new javax.swing.JButton();
        BtnAngka6 = new javax.swing.JButton();
        BtnKurang = new javax.swing.JButton();
        BtnAngka1 = new javax.swing.JButton();
        BtnAngka2 = new javax.swing.JButton();
        BtnAngka3 = new javax.swing.JButton();
        BtnTambah = new javax.swing.JButton();
        BtnKoma = new javax.swing.JButton();
        BtnAngka0 = new javax.swing.JButton();
        TxtSamaDengan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TxtHasil.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtHasilActionPerformed(evt);
            }
        });

        BtnCancel1.setText("C");
        BtnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancel1ActionPerformed(evt);
            }
        });

        BtnBagi.setText("/");
        BtnBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBagiActionPerformed(evt);
            }
        });

        BtnAngka7.setText("7");
        BtnAngka7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka7ActionPerformed(evt);
            }
        });

        BtnAngka8.setText("8");
        BtnAngka8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka8ActionPerformed(evt);
            }
        });

        BtnAngka9.setText("9");
        BtnAngka9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka9ActionPerformed(evt);
            }
        });

        BtnKali.setText("X");
        BtnKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKaliActionPerformed(evt);
            }
        });

        BtnAngka4.setText("4");
        BtnAngka4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka4ActionPerformed(evt);
            }
        });

        BtnAngka5.setText("5");
        BtnAngka5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka5ActionPerformed(evt);
            }
        });

        BtnAngka6.setText("6");
        BtnAngka6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka6ActionPerformed(evt);
            }
        });

        BtnKurang.setText("-");
        BtnKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKurangActionPerformed(evt);
            }
        });

        BtnAngka1.setText("1");
        BtnAngka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka1ActionPerformed(evt);
            }
        });

        BtnAngka2.setText("2");
        BtnAngka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka2ActionPerformed(evt);
            }
        });

        BtnAngka3.setText("3");
        BtnAngka3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka3ActionPerformed(evt);
            }
        });

        BtnTambah.setText("+");
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });

        BtnKoma.setText(",");
        BtnKoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKomaActionPerformed(evt);
            }
        });

        BtnAngka0.setText("0");
        BtnAngka0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAngka0ActionPerformed(evt);
            }
        });

        TxtSamaDengan.setText("=");
        TxtSamaDengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSamaDenganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtHasil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnCancel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(236, 236, 236))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnAngka7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnAngka8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnAngka4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnAngka5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnAngka9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnKali, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnAngka6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnAngka1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnAngka2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(BtnAngka0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BtnAngka3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnKoma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TxtSamaDengan, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TxtHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCancel1)
                    .addComponent(BtnBagi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAngka7)
                    .addComponent(BtnAngka8)
                    .addComponent(BtnAngka9)
                    .addComponent(BtnKali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAngka4)
                    .addComponent(BtnAngka5)
                    .addComponent(BtnAngka6)
                    .addComponent(BtnKurang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAngka1)
                    .addComponent(BtnAngka2)
                    .addComponent(BtnAngka3)
                    .addComponent(BtnTambah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnKoma)
                    .addComponent(BtnAngka0)
                    .addComponent(TxtSamaDengan))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBagiActionPerformed
     Angka1=Double.parseDouble(Angka);
     TxtHasil.setText("/");
     Angka="";
     Pilih=4;
    }//GEN-LAST:event_BtnBagiActionPerformed

    private void BtnAngka7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka7ActionPerformed
     Angka+= "7";
     TxtHasil.setText(Angka);
    }//GEN-LAST:event_BtnAngka7ActionPerformed

    private void BtnAngka8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka8ActionPerformed
     Angka+= "8";
     TxtHasil.setText(Angka);
    }//GEN-LAST:event_BtnAngka8ActionPerformed

    private void BtnAngka9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka9ActionPerformed
     Angka+= "9";
     TxtHasil.setText(Angka);
    }//GEN-LAST:event_BtnAngka9ActionPerformed

    private void BtnKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKaliActionPerformed
     Angka1=Double.parseDouble(Angka);
     TxtHasil.setText("*");
     Angka="";
     Pilih=3;
    }//GEN-LAST:event_BtnKaliActionPerformed

    private void BtnAngka4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka4ActionPerformed
     Angka+= "4";
     TxtHasil.setText(Angka);
    }//GEN-LAST:event_BtnAngka4ActionPerformed

    private void BtnAngka5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka5ActionPerformed
     Angka+= "5";
     TxtHasil.setText(Angka);
    }//GEN-LAST:event_BtnAngka5ActionPerformed

    private void BtnAngka6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka6ActionPerformed
     Angka+= "6";
     TxtHasil.setText(Angka);
    }//GEN-LAST:event_BtnAngka6ActionPerformed

    private void BtnKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKurangActionPerformed
     Angka1=Double.parseDouble(Angka);
     TxtHasil.setText("-");
     Angka="";
     Pilih=2;
    }//GEN-LAST:event_BtnKurangActionPerformed

    private void BtnAngka1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka1ActionPerformed
     Angka+= "1";
     TxtHasil.setText(Angka);
    }//GEN-LAST:event_BtnAngka1ActionPerformed

    private void BtnAngka2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka2ActionPerformed
     Angka+= "2";
     TxtHasil.setText(Angka);
    }//GEN-LAST:event_BtnAngka2ActionPerformed

    private void BtnAngka3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka3ActionPerformed
     Angka+= "3";
     TxtHasil.setText(Angka);
    }//GEN-LAST:event_BtnAngka3ActionPerformed

    private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
    Angka1=Double.parseDouble(Angka);
      TxtHasil.setText("+");
      Angka="";
      Pilih=1;
    }//GEN-LAST:event_BtnTambahActionPerformed

    private void BtnKomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKomaActionPerformed
     Angka+= ".";
     TxtHasil.setText(Angka);
    }//GEN-LAST:event_BtnKomaActionPerformed

    private void BtnAngka0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAngka0ActionPerformed
     Angka+= "0";
     TxtHasil.setText(Angka);
    }//GEN-LAST:event_BtnAngka0ActionPerformed

    private void TxtSamaDenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSamaDenganActionPerformed
    switch(Pilih){
        case 1:
            Angka2 = Double.parseDouble(Angka);
            Jumlah = Angka1 + Angka2;
            Angka = Double.toString(Jumlah);
            TxtHasil.setText(Angka);
            break;
        case 2:
            Angka2 = Double.parseDouble(Angka);
            Jumlah = Angka1 - Angka2;
            Angka = Double.toString(Jumlah);
            TxtHasil.setText(Angka);
            break;
        case 3:
            Angka2 = Double.parseDouble(Angka);
            Jumlah = Angka1 * Angka2;
            Angka = Double.toString(Jumlah);
            TxtHasil.setText(Angka);
            break;
        case 4:
            Angka2 = Double.parseDouble(Angka);
            Jumlah = Angka1 / Angka2;
            Angka = Double.toString(Jumlah);
            TxtHasil.setText(Angka);
            break;
            default:
            break;
            }
    }//GEN-LAST:event_TxtSamaDenganActionPerformed

    private void TxtHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtHasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtHasilActionPerformed

    private void BtnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancel1ActionPerformed
    TxtHasil.setText("");
      Angka1=0.0;
      Angka2=0.0;
      Jumlah=0.0;
      Angka="";
    }//GEN-LAST:event_BtnCancel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAngka0;
    private javax.swing.JButton BtnAngka1;
    private javax.swing.JButton BtnAngka2;
    private javax.swing.JButton BtnAngka3;
    private javax.swing.JButton BtnAngka4;
    private javax.swing.JButton BtnAngka5;
    private javax.swing.JButton BtnAngka6;
    private javax.swing.JButton BtnAngka7;
    private javax.swing.JButton BtnAngka8;
    private javax.swing.JButton BtnAngka9;
    private javax.swing.JButton BtnBagi;
    private javax.swing.JButton BtnCancel1;
    private javax.swing.JButton BtnKali;
    private javax.swing.JButton BtnKoma;
    private javax.swing.JButton BtnKurang;
    private javax.swing.JButton BtnTambah;
    private javax.swing.JTextField TxtHasil;
    private javax.swing.JButton TxtSamaDengan;
    // End of variables declaration//GEN-END:variables
}
